// TODO (T4 - Sanshubh): Finalize and lock down these data models. Add validation logic.

/**
 * Represents a user of the application.
 */
export interface User {
  _id: string;
  email: string;
  favorites: string[]; // Array of VideoRecipe _id's
  createdAt: Date;
}

/**
 * Represents the output from the Gemini Vision API after analyzing images.
 */
export interface IngredientDetection {
  _id: string;
  userId: string;
  items: { name: string; confidence: number }[];
  tags: string[];
  signature: string; // A unique hash representing the detected items+tags
  createdAt: Date;
}

/**
 * Represents a recipe generated by the AI, ready for video creation.
 */
export interface RecipeDraft {
  _id: string;
  signature: string;
  title: string;
  description: string;
  ingredients: { name: string }[];
  steps: string[];
  tags: string[];
  shotPlan: { step: number; action: string; durationSec: number }[];
  status: 'pending' | 'ready' | 'error';
}

/**
 * Represents the final, generated video recipe.
 */
export interface VideoRecipe {
  _id: string;
  signature: string;
  draftId: string;
  title: string;
  description: string;
  ingredients: { name: string }[];
  steps: string[];
  videoUrl: string;
  captions?: string[];
  durationSec: number;
  metrics?: { plays: number; likes: number };
  createdAt: Date;
}

/**
 * Type for just the ingredient and tag data from Gemini
 */
export type VisionData = {
    items: { name: string; confidence: number }[];
    tags: string[];
}

/**
 * Type for a single recipe idea from Gemini
 */
export type RecipeIdea = {
    title: string;
    description: string;
}

/**
 * Type for the full, structured response from the Gemini analysis call.
 */
export type GeminiAnalysisResponse = {
    visionData: VisionData;
    recipeIdeas: RecipeIdea[];
}