// ============================================================================
// @file: shared.ts
// @description: Unified type definitions for Cognition Kitchen / Foogle AI
// ============================================================================

// TODO (T4 - Sanshubh): Finalize and lock down these data models. Add validation logic.

/**
 * Represents a user of the application.
 */
export interface User {
  _id: string;
  email: string;
  favorites: string[]; // Array of VideoRecipe _id's
  createdAt: Date;
}

/**
 * Represents ingredient + tag data detected from Gemini Vision.
 */
export interface VisionData {
  items: { name: string; confidence: number }[];
  tags: string[];
}

/**
 * Represents a complete recipe generated by Gemini in a single step.
 */
export interface Recipe {
  _id?: string;
  title: string;
  description: string;
  ingredients: { name: string; quantity?: string }[];
  steps: string[];
  tags?: string[];
  cookTime?: string;
  difficulty?: 'easy' | 'medium' | 'hard';
}

/**
 * Represents the full structured response from Gemini (Vision + Recipes).
 */
export interface GeminiAnalysisResponse {
  visionData: VisionData;
  recipes: Recipe[];
}

/**
 * Represents a generated video version of a recipe.
 * (Simulated or produced via Veo + ElevenLabs)
 */
export interface VideoRecipe {
  _id: string;
  title: string;
  description: string;
  ingredients: { name: string; quantity?: string }[];
  steps: string[];
  videoUrl: string;
  captions?: string[];
  durationSec?: number;
  metrics?: { plays: number; likes: number };
  tags?: string[];
  cookTime?: string;
  difficulty?: 'easy' | 'medium' | 'hard';
  createdAt?: Date;
}

/**
 * Represents the old-style draft recipe (optional, legacy).
 * Can be removed once all services migrate to the new single-step flow.
 */
export interface RecipeDraft {
  _id: string;
  title: string;
  description: string;
  ingredients: { name: string; quantity?: string }[];
  steps: string[];
  tags?: string[];
  shotPlan?: { step: number; action: string; durationSec: number }[];
  status?: 'pending' | 'ready' | 'error';
  signature?: string;
}
