import { VideoRecipe } from '../types/shared';
import { MOCK_VIDEO_RECIPE } from '../data/mocks';

/**
 * Simulates generating a short video from a full recipe.
 * In a real implementation, this would queue a job that:
 *  - Calls Google Veo for visuals
 *  - Calls ElevenLabs for narration
 *  - Merges and uploads the final result
 * @param recipe - The full recipe generated by Gemini.
 * @returns A promise resolving to a VideoRecipe.
 */
export const generateVideo = (recipe: any): Promise<VideoRecipe> => {
  console.log(`🎬 Generating video for recipe: ${recipe.title}`);

  return new Promise(resolve => {
    setTimeout(() => {
      const video: VideoRecipe = {
        ...MOCK_VIDEO_RECIPE,
        _id: `vid_${Date.now()}`,
        title: recipe.title,
        description: recipe.description,
        ingredients: recipe.ingredients,
        steps: recipe.steps,
        tags: recipe.tags || [],
        cookTime: recipe.cookTime || 'N/A',
        difficulty: recipe.difficulty || 'medium',
      };
      console.log('✅ Video recipe generated:', video);
      resolve(video);
    }, 3000); // Simulated render delay
  });
};
